name: Build Expo APK on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY}}

      - name: Build APK on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            # Navigate to project folder or clone fresh
            cd /home/ubuntu/app || mkdir /home/ubuntu/app && cd /home/ubuntu/app
            git pull origin main || git clone https://github.com/Adjanour/kunu-tech.git .

            # Install dependencies
            yarn install

            # Build APK locally on EC2
            eas build --platform android --profile preview --non-interactive --local

            # Find APK and move it to a known location
            mkdir -p /home/ubuntu/builds
            cp $(find . -name "*.apk" | head -n 1) /home/ubuntu/builds/app.apk
          EOF

      - name: Upload APK to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_BUCKET: "kunu-expo"
        run: |
          scp -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/builds/app.apk .
          aws s3 cp app.apk s3://$AWS_BUCKET/app.apk --acl public-read
          echo "Download Link: https://$AWS_BUCKET.s3.amazonaws.com/app.apk"

      - name: Notify on Success
        run: echo "APK Build & Deployment Complete!"
